<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "купить вино в минске");
$APPLICATION->SetPageProperty("title", "Отзывы о сети магазинов \"Вино\"");
$APPLICATION->SetTitle("Отзывы о сети магазинов \"Вино\"");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"page_reviews",
	array(
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "12",
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "MAIL",
			1 => "NAME",
			2 => "RATING",
			3 => "PHONE",
			4 => "",
		),
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"COMPONENT_TEMPLATE" => "page_reviews"
	),
	false
);?>




<?
$rsSites = CSite::GetByID("s1");
$arSite = $rsSites->Fetch();

$mail =$arSite["EMAIL"];
$APPLICATION->IncludeComponent(
	"slam:easyform", 
	"form", 
	array(
		"BCC" => "",
		"CATEGORY_EMAIL_PLACEHOLDER" => "",
		"CATEGORY_EMAIL_TITLE" => "Ваш E-mail",
		"CATEGORY_EMAIL_TYPE" => "email",
		"CATEGORY_EMAIL_TYPE_VALIDATION" => "",
		"CATEGORY_EMAIL_VALUE" => "",
		"CATEGORY_MESSAGE_PLACEHOLDER" => "",
		"CATEGORY_MESSAGE_TITLE" => "Сообщение",
		"CATEGORY_MESSAGE_TYPE" => "textarea",
		"CATEGORY_MESSAGE_TYPE_VALIDATION" => "",
		"CATEGORY_MESSAGE_VALUE" => "",
		"CATEGORY_PHONE_PLACEHOLDER" => "",
		"CATEGORY_PHONE_TITLE" => "Мобильный телефон",
		"CATEGORY_PHONE_TYPE" => "tel",
		"CATEGORY_PHONE_TYPE_VALIDATION" => "",
		"CATEGORY_PHONE_VALUE" => "",
		"CATEGORY_TITLE_PLACEHOLDER" => "",
		"CATEGORY_TITLE_TITLE" => "Ваше имя",
		"CATEGORY_TITLE_TYPE" => "text",
		"CATEGORY_TITLE_TYPE_VALIDATION" => "",
		"CATEGORY_TITLE_VALUE" => "",
		"CATEGORY_WORK_COMPANY_PLACEHOLDER" => "",
		"CATEGORY_WORK_COMPANY_TITLE" => "Компания",
		"CATEGORY_WORK_COMPANY_TYPE" => "text",
		"CATEGORY_WORK_COMPANY_TYPE_VALIDATION" => "",
		"CATEGORY_WORK_COMPANY_VALUE" => "",
		"DISABLE_SEND_MAIL" => "N",
		"DISPLAY_FIELDS" => array(
			0 => "TITLE",
			1 => "EMAIL",
			2 => "PHONE",
			3 => "MESSAGE",
			4 => "RATING",
			5 => "ITEM_NAME",
			6 => "PHOTO",
			7 => "",
		),
		"EMAIL_TO" => $mail,
		"ERROR_TEXT" => "Произошла ошибка. Сообщение не отправлено.",
		"EVENT_MESSAGE_ID" => array(
			0 => "31",
		),
		"FIELDS_ORDER" => "TITLE,PHONE,EMAIL,PHOTO,RATING,ITEM_NAME,MESSAGE",
		"FORM_AUTOCOMPLETE" => "Y",
		"FORM_ID" => "callback-modal",
		"FORM_SUBMIT_VALUE" => "Отправить",
		"HIDE_ASTERISK" => "N",
		"HIDE_FIELD_NAME" => "N",
		"MAIL_SEND_USER" => "N",
		"MAIL_SUBJECT_ADMIN" => "#SITE_NAME#: Сообщение из формы в отзывах",
		"OK_TEXT_TITLE" => "Спасибо за ваш отзыв!",
		"OK_TEXT" => "Нам очень важно ваше мнение. Спасибо, что делитесь им с нами.",
		"OK_TEXT_AFTER" => "",
		"REPLACE_FIELD_FROM" => "N",
		"REQUIRED_FIELDS" => array(
			0 => "TITLE",
			1 => "EMAIL",
			2 => "PHONE",
			3 => "RATING",
			4 => "ITEM_NAME",
		),
		"USE_BOOTSRAP_CSS" => "Y",
		"USE_BOOTSRAP_JS" => "N",
		"USE_CAPTCHA" => "N",
		"USE_JQUERY" => "N",
		"WIDTH_FORM" => "",
		"WRITE_MESS_FILDES_TABLE" => "N",
		"COMPONENT_TEMPLATE" => "form",
		"CATEGORY_RATING_TITLE" => "Оценка",
		"CATEGORY_RATING_TYPE" => "rating",
		"CATEGORY_RATING_PLACEHOLDER" => "",
		"CATEGORY_RATING_VALUE" => "",
		"CATEGORY_ITEM_NAME_TITLE" => "Заголовок",
		"CATEGORY_ITEM_NAME_TYPE" => "text",
		"CATEGORY_ITEM_NAME_PLACEHOLDER" => "",
		"CATEGORY_ITEM_NAME_VALUE" => "",
		"CATEGORY_PHOTO_TITLE" => "Добавить фото",
		"CATEGORY_PHOTO_TYPE" => "file",
		"CATEGORY_PHOTO_PLACEHOLDER" => "",
		"CATEGORY_PHOTO_VALUE" => "",
		"CATEGORY_RATING_TYPE_VALIDATION" => "",
		"CATEGORY_ITEM_NAME_TYPE_VALIDATION" => "",
		"CATEGORY_PHOTO_TYPE_VALIDATION" => "",
		"DETAIL_RECORD_IBLOCK" => "Y",
		"IBLOCK_ID_RECORD" => "12"
	),
	false
);?>




<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>