<?$APPLICATION->IncludeComponent(
	"energosoft:energosoft.group_property_manual", 
	".default", 
	array(
		"CACHE_NOTES" => "",
		"CACHE_TIME" => "36000000000",
		"CACHE_TYPE" => "A",
		"ES_ELEMENT" => $arParams["ITEM_ID"],
		"ES_GROUP_COUNT" => "6",
		"ES_IBLOCK_CATALOG" => "5",
		"ES_IBLOCK_TYPE_CATALOG" => "catalog",
		"ES_REMOVE_HREF" => "N",
		"ES_SHOW_EMPTY" => "N",
		"ES_SHOW_EMPTY_PROPERTY" => "N",
		"COMPONENT_TEMPLATE" => ".default",
		"ES_GROUP_NAME_0" => "Общее",
		"ES_GROUP_0" => array(
			0 => "MANUFACTURE",
			1 => "NEW_OPT",
			2 => "NEW_OPT1",
			3 => "COUNT",
		),
		"ES_GROUP_NAME_1" => "Назначение",
		"ES_GROUP_1" => array(
			0 => "WASH",
			1 => "MAT",
			2 => "N134",
			3 => "FORM",
			4 => "COL",
		),
		"ES_GROUP_NAME_2" => "Характеристика",
		"ES_GROUP_2" => array(
			0 => "V2",
			1 => "V1",
			2 => "VT1",
			3 => "DI",
			4 => "DI1",
			5 => "DI2",
			6 => "VOL1",
			7 => "PACK",
		),
		"ES_GROUP_NAME_3" => "",
		"ES_GROUP_3" => array(
			0 => "COUNT",
			1 => "ARTPR",
			2 => "TIP",
		),
		"ES_GROUP_NAME_4" => "Характеристики",
		"ES_GROUP_4" => array(
			0 => "PURPOSE",
			1 => "VVS",
			2 => "VFVS",
			3 => "YP",
			4 => "DIA",
			5 => "KV",
			6 => "KT",
			7 => "BOT",
			8 => "PLA",
			9 => "NPS",
			10 => "PV",
			11 => "SZ",
			12 => "TDVS",
			13 => "TDR",
			14 => "TNVS",
			15 => "TPVS",
			16 => "TSO",
			17 => "UV",
			18 => "CVNS",
			19 => "CVS",
		),
		"ES_GROUP_NAME_5" => "Технические характеристики",
		"ES_GROUP_5" => array(
			0 => "VSHKVU",
			1 => "VSHK",
			2 => "VSHVU",
			3 => "VIS",
			4 => "GARM",
			5 => "GLSHVU",
			6 => "GLSH",
			7 => "SHSHVU",
			8 => "SHSH",
		)
	),
	false
);?>